name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # Do not deploy in the main repository, only in user projects
    if: github.repository_owner != 'fastapi'
    runs-on:
      - self-hosted
      - staging
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup environment
        run: |
          cp .env.example .env
          sed -i "s/ENVIRONMENT=local/ENVIRONMENT=staging/g" .env
          
      - name: Build with Docker Compose
        run: docker compose -f docker-compose.yml build
          
      - name: Deploy with Docker Compose
        run: docker compose -f docker-compose.yml up -d
